In [ ]:
import torch
import torchvision
from torch.autograd import Variable

In [145]:
#make test data
import numpy as np
x=np.arange(100,dtype=np.float32)
y=2*x+3

In [163]:
x=(x-x.mean())/x.std()
y=(y-y.mean())/y.std()
print(x,y,sep="\n")

[-1.7148161  -1.6801733  -1.6455306  -1.6108878  -1.5762451  -1.5416024
 -1.5069596  -1.4723169  -1.437674   -1.4030313  -1.3683885  -1.3337458
 -1.299103   -1.2644603  -1.2298176  -1.1951748  -1.1605321  -1.1258893
 -1.0912466  -1.0566038  -1.0219611  -0.98731834 -0.9526756  -0.9180328
 -0.88339007 -0.8487473  -0.8141046  -0.77946186 -0.7448191  -0.71017635
 -0.6755336  -0.64089084 -0.6062481  -0.5716053  -0.5369626  -0.5023199
 -0.46767712 -0.43303436 -0.3983916  -0.36374885 -0.32910612 -0.29446337
 -0.2598206  -0.22517787 -0.19053511 -0.15589237 -0.12124962 -0.08660688
 -0.05196412 -0.01732137  0.01732137  0.05196412  0.08660688  0.12124962
  0.15589237  0.19053511  0.22517787  0.2598206   0.29446337  0.32910612
  0.36374885  0.3983916   0.43303436  0.46767712  0.5023199   0.5369626
  0.5716053   0.6062481   0.64089084  0.6755336   0.71017635  0.7448191
  0.77946186  0.8141046   0.8487473   0.88339007  0.9180328   0.9526756
  0.98731834  1.0219611   1.0566038   1.0912466   1.1258893

In [164]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [194]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.layer1=nn.Linear(1,3)
        self.layer2=nn.Linear(3,1) 
    def forward(self,x):
        x=self.layer1(x)
        x=self.layer2(x)
        return x

In [195]:
network=Net()
opt=optim.SGD(network.parameters(),lr=0.01,momentum=0.1)

In [202]:
def train():
    global x,y
    for i in range(1000):
        network.zero_grad()
        outputs=network(torch.from_numpy(x).view([-1,1]))
        loss=F.mse_loss(outputs,torch.from_numpy(y))
        print(loss)
        loss.backward()
        opt.step()
train()

tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., g

tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., g

tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., grad_fn=<MseLossBackward>)
tensor(1., g

In [206]:
y[50:55]

array([0.01732137, 0.05196412, 0.08660688, 0.12124962, 0.15589237],
      dtype=float32)

In [207]:
network(torch.from_numpy(x[50:55]).view([-1,1]))

tensor([[-2.2352e-08],
        [-1.1176e-08],
        [ 2.6077e-08],
        [ 9.6858e-08],
        [ 1.0431e-07]], grad_fn=<AddmmBackward>)

In [49]:
xx

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47],
        [48],
        [49],
        [50],
        [51],
        [52],
        [53],
        [54],
        [55],
        [56],
        [57],
        [58],
        [59],
        [60],
        [61],
        [62],
        [63],
        [64],
        [65],
        [66],
        [67],
        [68],
        [69],
        [70],
      